console.log ("******𝑹𝒆𝒑𝒐𝒓𝒕 𝑪𝒂𝒓𝒅******")
console.log("𝑵𝒂𝒎𝒆 : 𝑯𝒂𝒓𝒔𝒉𝒂𝒍 𝒃𝒉𝒂𝒘𝒔𝒂𝒓")
console.log("𝑺𝒄𝒉𝒐𝒐𝒍 : 𝑺𝑲𝑺 𝑰𝒏𝒕𝒆𝒓𝒏𝒂𝒕𝒊𝒐𝒏 𝒔𝒄𝒉𝒐𝒐𝒍")
console.log("𝑮𝒓𝒂𝒅𝒆 : 𝑨+")
console.log("𝑺𝒆𝒄𝒕𝒊𝒐𝒏 : 𝑨")
console.log("𝑹𝒐𝒍𝒍 𝒏𝒐 : 1")
console.log("＃＃𝙈𝙖𝙧𝙠𝙨＃＃")
console.log("𝑯𝒊𝒔𝒕𝒐𝒓𝒚 : 90")
console.log("𝑬𝒏𝒈𝒍𝒊𝒔𝒉 : 90")
console.log("𝑺𝒄𝒊𝒆𝒏𝒄𝒆 : 80")